version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: antd
    versions:
    - 4.11.1
    - 4.11.2
    - 4.12.2
    - 4.12.3
    - 4.13.0
    - 4.13.1
    - 4.14.0
    - 4.15.0
    - 4.15.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: react-map-gl
    versions:
    - 6.0.3
    - 6.1.1
    - 6.1.10
    - 6.1.11
    - 6.1.5
    - 6.1.7
    - 6.1.9
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: algoliasearch
    versions:
    - 4.8.4
    - 4.8.5
    - 4.8.6
  - dependency-name: react-instantsearch-dom
    versions:
    - 6.10.0
    - 6.8.3
    - 6.9.0
  - dependency-name: qs
    versions:
    - 6.9.6
  - dependency-name: "@types/react"
    versions:
    - 16.14.2
    - 16.14.3
    - 16.14.4
  - dependency-name: "@emotion/babel-preset-css-prop"
    versions:
    - 11.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
