parser: babel-eslint
plugins:
  - react
extends:
  - prettier
  - plugin:react/recommended
parserOptions:
  ecmaFeatures: { jsx: true }
env:
  browser: true
  es6: true
  node: true
rules:
  strict: 0
  indent: [2, 2, { SwitchCase: 1 }]
  semi: [2, always]
  no-extra-semi: 2
  no-irregular-whitespace: 2
  no-mixed-spaces-and-tabs: 2
  semi-spacing: [2, { before: false, after: true }]
  eqeqeq: 2
  comma-dangle: [2, never]
  comma-spacing: [2, { before: false, after: true }]
  space-in-parens: [2, never]
  space-before-function-paren:
    [2, { anonymous: never, named: never, asyncArrow: always }]
  space-before-blocks: 2
  keyword-spacing: 2
  no-unneeded-ternary: 2
  curly: [2, multi-line]
  space-infix-ops: 2
  no-else-return: [2, { allowElseIf: true }]
  multiline-ternary: [2, always-multiline]
  key-spacing: [2, { mode: strict }]
  arrow-parens: [2, always]
  react/jsx-wrap-multilines: 2
  prefer-const: 2
  no-debugger: 2
  react/jsx-filename-extension: 0
  react/jsx-curly-brace-presence: 0
  react/prop-types: 0
  react/destructuring-assignment: 0
  react/no-unused-state: 0
  react/style-prop-object: 0
  react/sort-comp: 0
  react/display-name: 0
  import/prefer-default-export: 0
  no-nested-ternary: 0
  camelcase: 0
  no-unused-vars: 0
  import/order: 0
